export interface Product {
  id: string;
  name: string;
  price: number;
  oldPrice?: number;
  image: string;
  category: string;
  isFeatured: boolean;
  description: string;
  brand: string;
  inStock: boolean;
}

// Updated working perfume bottle images
const IMG = {
  a: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&q=80&w=800",
  b: "https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=800",
  c: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=800",
  d: "https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&q=80&w=800",
  e: "https://images.unsplash.com/photo-1610461888750-10bfc601b874?auto=format&fit=crop&q=80&w=800",
  f: "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&q=80&w=800",
};

export const products: Product[] = [
  {
    id: "1",
    name: "Oud Royale",
    price: 120,
    oldPrice: 150,
    image: IMG.c,
    category: "Unisex",
    isFeatured: true,
    description: "A majestic blend of rare agarwood, amber, and warm spices.",
    brand: "Xerjoff",
    inStock: true,
  },
  {
    id: "2",
    name: "Midnight Rose",
    price: 95,
    oldPrice: 120,
    image: IMG.b,
    category: "Women",
    isFeatured: true,
    description: "An enchanting nocturnal floral fragrance of velvet roses.",
    brand: "Amouage",
    inStock: true,
  },
  {
    id: "3",
    name: "Aqua Marine",
    price: 85,
    image: IMG.e,
    category: "Men",
    isFeatured: true,
    description: "The ultimate expression of ocean-fresh freshness.",
    brand: "Amouage",
    inStock: true,
  },
  {
    id: "5",
    name: "Velvet Santal",
    price: 110,
    image: IMG.d,
    category: "Unisex",
    isFeatured: false,
    description: "A smooth, creamy blend of Australian sandalwood.",
    brand: "Akro",
    inStock: true,
  },
  {
    id: "6",
    name: "Azure Breeze",
    price: 75,
    oldPrice: 95,
    image: IMG.f,
    category: "Men",
    isFeatured: false,
    description: "The refreshing spirit of the Mediterranean.",
    brand: "Alghabra",
    inStock: true,
  },
  {
    id: "7",
    name: "Silk Peony",
    price: 105,
    image: IMG.a,
    category: "Women",
    isFeatured: false,
    description: "A delicate dance of soft petals with blooming peonies.",
    brand: "Affinessence",
    inStock: true,
  },
  {
    id: "9",
    name: "Mystic Musk",
    price: 90,
    image: IMG.b,
    category: "Unisex",
    isFeatured: true,
    description: "An ethereal, skin-like scent of white musk.",
    brand: "Amouage",
    inStock: true,
  },
  {
    id: "10",
    name: "Midnight Jasmine",
    price: 115,
    oldPrice: 145,
    image: IMG.a,
    category: "Women",
    isFeatured: true,
    description: "The intoxicating allure of night-blooming jasmine.",
    brand: "24",
    inStock: true,
  },
  {
    id: "11",
    name: "Saffron Spices",
    price: 135,
    image: IMG.c,
    category: "Unisex",
    isFeatured: true,
    description: "A warm, radiant blend of Persian saffron and leather.",
    brand: "Xerjoff",
    inStock: true,
  },
  {
    id: "12",
    name: "Blue Vertigo",
    price: 88,
    image: IMG.e,
    category: "Men",
    isFeatured: true,
    description: "A dizzying rush of alpine air, mint and oakmoss.",
    brand: "Amouage",
    inStock: true,
  },
  {
    id: "13",
    name: "Rose Quartz",
    price: 102,
    oldPrice: 130,
    image: IMG.f,
    category: "Women",
    isFeatured: true,
    description: "A sparkling blend of Turkish rose, lychee and white cedar.",
    brand: "Agatho",
    inStock: true,
  },
  {
    id: "15",
    name: "Citrus Grove",
    price: 72,
    image: IMG.d,
    category: "Men",
    isFeatured: true,
    description: "A sun-drenched walk through an Italian citrus grove.",
    brand: "Alghabra",
    inStock: true,
  },
];